import uuid
from typing import Any
from unittest.mock import MagicMock

from fastapi.testclient import TestClient
from sqlalchemy.orm import Session

from app.models.scan import Scan, ScanStatus
from app.models.target import Target

# `mock_run_scan_task_apply_async` and `mock_celery_control_revoke`
# (conftest.py) are both autouse, so every `POST /scans` and `/cancel` call
# in this file already avoids a real broker round trip without any of these
# tests needing to request them explicitly - they're only requested by name
# below where a test needs to assert against (or reconfigure) the mock
# itself.


def _create_authorized_target(client: TestClient) -> dict[str, Any]:
    project = client.post("/api/v1/projects", json={"name": "Scan Project"}).json()
    target = client.post(
        f"/api/v1/projects/{project['id']}/targets",
        json={
            "value": "10.0.0.10",
            "target_type": "ip",
            "authorization_confirmed": True,
        },
    ).json()
    return {"project": project, "target": target}


def _create_scan(client: TestClient, ctx: dict[str, Any]) -> dict[str, Any]:
    resp = client.post(
        "/api/v1/scans",
        json={"project_id": ctx["project"]["id"], "target_id": ctx["target"]["id"]},
    )
    assert resp.status_code == 201
    return resp.json()


def test_create_scan_against_authorized_target_succeeds(client: TestClient) -> None:
    ctx = _create_authorized_target(client)

    resp = client.post(
        "/api/v1/scans",
        json={"project_id": ctx["project"]["id"], "target_id": ctx["target"]["id"]},
    )

    assert resp.status_code == 201
    assert resp.json()["status"] == "queued"


def test_create_scan_rejected_for_target_with_authorization_revoked(
    client: TestClient, db: Session
) -> None:
    ctx = _create_authorized_target(client)

    # Bypass the API to flip authorization directly via the DB session,
    # simulating a target record whose authorization was revoked after
    # creation. TargetCreate's Pydantic validator can't catch this - it
    # only runs at target-creation time - so this exercises the
    # service-layer defense-in-depth check in scan_service.create_scan.
    target_row = db.get(Target, uuid.UUID(ctx["target"]["id"]))
    assert target_row is not None
    target_row.authorization_confirmed = False
    db.commit()

    resp = client.post(
        "/api/v1/scans",
        json={"project_id": ctx["project"]["id"], "target_id": ctx["target"]["id"]},
    )

    assert resp.status_code == 400


def test_scan_status_endpoint_reflects_status(client: TestClient) -> None:
    ctx = _create_authorized_target(client)
    scan = _create_scan(client, ctx)

    resp = client.get(f"/api/v1/scans/{scan['id']}/status")

    assert resp.status_code == 200
    assert resp.json()["status"] == "queued"


def test_cancel_created_scan_transitions_to_cancelled(client: TestClient) -> None:
    ctx = _create_authorized_target(client)
    scan = _create_scan(client, ctx)

    resp = client.post(f"/api/v1/scans/{scan['id']}/cancel")

    assert resp.status_code == 200
    assert resp.json()["status"] == "cancelled"


def test_cancel_already_cancelled_scan_returns_409(client: TestClient) -> None:
    ctx = _create_authorized_target(client)
    scan = _create_scan(client, ctx)
    first_cancel = client.post(f"/api/v1/scans/{scan['id']}/cancel")
    assert first_cancel.status_code == 200

    resp = client.post(f"/api/v1/scans/{scan['id']}/cancel")

    assert resp.status_code == 409


def test_create_scan_rejects_target_from_a_different_project(client: TestClient) -> None:
    """Cross-tenant authorization boundary: a target_id that exists but
    belongs to a project other than the project_id in the request body must
    be rejected, not silently accepted against the wrong project.
    scan_service.create_scan already enforces `target.project_id !=
    data.project_id` -> NotFoundError, but this had zero test coverage.
    """
    ctx_a = _create_authorized_target(client)
    project_b = client.post("/api/v1/projects", json={"name": "Other Project"}).json()

    resp = client.post(
        "/api/v1/scans",
        json={"project_id": project_b["id"], "target_id": ctx_a["target"]["id"]},
    )

    assert resp.status_code == 404


def test_create_scan_enqueues_task_and_stores_celery_task_id(
    client: TestClient, db: Session, mock_run_scan_task_apply_async: MagicMock
) -> None:
    """`celery_task_id` is an internal field, not exposed on `ScanRead` (see
    task-7 report for that decision), so it's checked via a direct DB read
    rather than the response body.

    The task id is now generated by `create_scan` itself (a `uuid4()`,
    passed to `apply_async(task_id=...)`) rather than read back off a
    Celery `AsyncResult`, so there's no fixed fake id to assert against -
    instead assert the DB-stored id is exactly the one `apply_async` was
    actually called with.
    """
    ctx = _create_authorized_target(client)

    resp = client.post(
        "/api/v1/scans",
        json={"project_id": ctx["project"]["id"], "target_id": ctx["target"]["id"]},
    )

    assert resp.status_code == 201
    body = resp.json()
    assert body["status"] == "queued"

    scan_row = db.get(Scan, uuid.UUID(body["id"]))
    assert scan_row is not None
    assert scan_row.celery_task_id is not None
    assert scan_row.status.value == "queued"

    mock_run_scan_task_apply_async.assert_called_once_with(
        args=[body["id"]], task_id=scan_row.celery_task_id
    )


def test_create_scan_commits_queued_status_before_dispatching_task(
    client: TestClient, db: Session, mock_run_scan_task_apply_async: MagicMock
) -> None:
    """Guards against the lost-update race the fix in `scan_service.create_scan`
    closes: `status=QUEUED` and `celery_task_id` must already be committed to
    the DB by the time `apply_async` is called, not after - otherwise a
    worker that started before the "after" commit landed could have its own
    (possibly much later) status write silently clobbered by it.

    Verified via `db.expire_all()` inside the `apply_async` mock's
    side_effect: that discards the session's cached attribute values and
    forces a fresh read from the DB, so it reflects whatever was last
    actually committed - not whatever is merely sitting on the in-memory
    `scan` object pending a future commit.
    """
    ctx = _create_authorized_target(client)
    observed: dict[str, Any] = {}

    def _check_db_state_at_dispatch_time(*args: Any, **kwargs: Any) -> MagicMock:
        scan_id = uuid.UUID(kwargs["args"][0])
        db.expire_all()
        row = db.get(Scan, scan_id)
        observed["status"] = row.status if row is not None else None
        observed["celery_task_id"] = row.celery_task_id if row is not None else None
        return MagicMock()

    mock_run_scan_task_apply_async.side_effect = _check_db_state_at_dispatch_time

    resp = client.post(
        "/api/v1/scans",
        json={"project_id": ctx["project"]["id"], "target_id": ctx["target"]["id"]},
    )

    assert resp.status_code == 201
    mock_run_scan_task_apply_async.assert_called_once()
    assert observed["status"] == ScanStatus.QUEUED
    assert observed["celery_task_id"] is not None


def test_cancel_queued_scan_revokes_celery_task(
    client: TestClient, db: Session, mock_celery_control_revoke: MagicMock
) -> None:
    ctx = _create_authorized_target(client)
    scan = _create_scan(client, ctx)
    scan_row = db.get(Scan, uuid.UUID(scan["id"]))
    assert scan_row is not None
    task_id = scan_row.celery_task_id
    assert task_id is not None

    resp = client.post(f"/api/v1/scans/{scan['id']}/cancel")

    assert resp.status_code == 200
    assert resp.json()["status"] == "cancelled"
    mock_celery_control_revoke.assert_called_once_with(task_id)


def test_get_scan_and_status_expose_error_message_for_failed_scan(
    client: TestClient, db: Session
) -> None:
    """Finding 4: `Scan.error_message` already exists on the model (Task 6)
    but was never exposed via the API - a caller polling a failed scan had
    no way to learn why. Both `GET /scans/{id}` and `GET /scans/{id}/status`
    must surface it once populated.
    """
    ctx = _create_authorized_target(client)
    scan = _create_scan(client, ctx)

    # Bypass the worker and flip the scan straight to FAILED with an
    # error_message, mirroring the DB-bypass pattern already used above for
    # authorization revocation - this test only cares about API exposure of
    # an already-populated column, not the orchestration logic that sets it
    # (covered separately in test_scan_orchestration.py).
    scan_row = db.get(Scan, uuid.UUID(scan["id"]))
    assert scan_row is not None
    scan_row.status = ScanStatus.FAILED
    scan_row.error_message = "nmap exited with status 1 scanning '10.0.0.10': boom"
    db.commit()

    get_resp = client.get(f"/api/v1/scans/{scan['id']}")
    assert get_resp.status_code == 200
    assert get_resp.json()["error_message"] == scan_row.error_message

    status_resp = client.get(f"/api/v1/scans/{scan['id']}/status")
    assert status_resp.status_code == 200
    assert status_resp.json()["error_message"] == scan_row.error_message


def test_get_scan_error_message_is_null_when_not_failed(client: TestClient) -> None:
    ctx = _create_authorized_target(client)
    scan = _create_scan(client, ctx)

    get_resp = client.get(f"/api/v1/scans/{scan['id']}")
    status_resp = client.get(f"/api/v1/scans/{scan['id']}/status")

    assert get_resp.json()["error_message"] is None
    assert status_resp.json()["error_message"] is None


def test_cancel_still_succeeds_when_revoke_raises(
    client: TestClient, mock_celery_control_revoke: MagicMock
) -> None:
    """The DB status change is the authoritative outcome of cancelling a
    scan - a broker error while revoking the Celery task must not prevent
    the cancel API call from succeeding.
    """
    mock_celery_control_revoke.side_effect = RuntimeError("broker down")
    ctx = _create_authorized_target(client)
    scan = _create_scan(client, ctx)

    resp = client.post(f"/api/v1/scans/{scan['id']}/cancel")

    assert resp.status_code == 200
    assert resp.json()["status"] == "cancelled"
