"""add assets, services tables; scan celery_task_id, error_message columns

Revision ID: 26de1feba77b
Revises: 111ce3c92341
Create Date: 2026-09-12 04:31:02.882342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26de1feba77b'
down_revision: Union[str, Sequence[str], None] = '111ce3c92341'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('target_id', sa.Uuid(), nullable=False),
    sa.Column('scan_id', sa.Uuid(), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_id'], ['targets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_project_id'), 'assets', ['project_id'], unique=False)
    op.create_index(op.f('ix_assets_scan_id'), 'assets', ['scan_id'], unique=False)
    op.create_index(op.f('ix_assets_target_id'), 'assets', ['target_id'], unique=False)
    op.create_table('services',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('protocol', sa.String(length=10), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('service_name', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_services_asset_id'), 'services', ['asset_id'], unique=False)
    op.add_column('scans', sa.Column('celery_task_id', sa.String(length=255), nullable=True))
    op.add_column('scans', sa.Column('error_message', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scans', 'error_message')
    op.drop_column('scans', 'celery_task_id')
    op.drop_index(op.f('ix_services_asset_id'), table_name='services')
    op.drop_table('services')
    op.drop_index(op.f('ix_assets_target_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_scan_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_project_id'), table_name='assets')
    op.drop_table('assets')
    # ### end Alembic commands ###
