"""initial schema: projects, targets, scans

Revision ID: 65c51fbe1258
Revises: 
Create Date: 2026-09-06 12:27:55.760047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '65c51fbe1258'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('targets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('target_type', sa.Enum('IP', 'DOMAIN', 'HOSTNAME', 'CIDR', name='target_type'), nullable=False),
    sa.Column('authorization_confirmed', sa.Boolean(), nullable=False),
    sa.Column('authorization_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scans',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('target_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'QUEUED', 'RUNNING', 'DISCOVERY', 'FINGERPRINTING', 'ANALYZING', 'CORRELATING', 'RISK_ANALYSIS', 'REPORT_GENERATION', 'COMPLETED', 'FAILED', 'CANCELLED', name='scan_status'), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_id'], ['targets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scans')
    op.drop_table('targets')
    op.drop_table('projects')
    # ### end Alembic commands ###
    # Manually adjusted: autogenerate does not emit DROP TYPE for the
    # Postgres enum types it creates via op.create_table, which would
    # otherwise leave `target_type` and `scan_status` orphaned after a
    # downgrade and break a subsequent upgrade with a "type already
    # exists" error.
    sa.Enum(name='scan_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='target_type').drop(op.get_bind(), checkfirst=True)
