"""add service fingerprint columns (product, version, extrainfo, fingerprint_source, evidence)

Revision ID: d6b7d6e6b8c8
Revises: 26de1feba77b
Create Date: 2026-09-17 08:38:45.307767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd6b7d6e6b8c8'
down_revision: Union[str, Sequence[str], None] = '26de1feba77b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('product', sa.String(length=255), nullable=True))
    op.add_column('services', sa.Column('version', sa.String(length=100), nullable=True))
    op.add_column('services', sa.Column('extrainfo', sa.Text(), nullable=True))
    op.add_column('services', sa.Column('fingerprint_source', sa.String(length=20), nullable=True))
    op.add_column('services', sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('services', 'evidence')
    op.drop_column('services', 'fingerprint_source')
    op.drop_column('services', 'extrainfo')
    op.drop_column('services', 'version')
    op.drop_column('services', 'product')
    # ### end Alembic commands ###
